name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/job-scraper:latest
    - name: Run scraper script
      run: docker run --rm -v ${{ github.workspace }}/data:/app/data ${{ secrets.DOCKER_USERNAME }}/job-scraper:latest python src/scraper.py
    - name: Run clean data script
      run: docker run --rm -v ${{ github.workspace }}/data:/app/data ${{ secrets.DOCKER_USERNAME }}/job-scraper:latest python src/clean_data.py
    - name: Run tests inside container
      run: docker run --rm -e PYTHONPATH=/app -v ${{ github.workspace }}/data:/app/data ${{ secrets.DOCKER_USERNAME }}/job-scraper:latest pytest
